version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - sqlite_data:/var/www/queuedb
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - DOCKER_DB_PATH=/var/www/queuedb/database.sqlite
    volumes:
      - .:/var/www/html
      - sqlite_data:/var/www/queuedb
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
